# Site settings
title: Patrick Stachofsky
email: patrickst@mac.com
description: > # this means to ignore newlines until "baseurl:"
  Yep, you guessed it, another collection of rablings and rantings about software engineering...
# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: pstachofsky
github_username:  patrickst1
stackoverflow_access:
  url: 231621/patrick
  username: patrickst1
linkedin_access:
  url: patrick-stachofsky/38/223/236
  username: patrickst1

# Build settings
markdown: kramdown
